# Site settings
title: Shubham Kumaram's Dev Blog
description: A blog about stuff I build and technologies I learn
url: "http://www.kumaram.dev"

# User settings
username: Shubham Kumaram
user_description: I am a final year student pursuing Bachelors of Engineering in Information Technology. I love learning and creating new things which can be used by people everywhere. Here I'd be sharing stuff I learn and also stuff I make. Stay tuned.
user_title: Software Developer
email: shubham@kumaram.dev
twitter_username: shubhamkrm
github_username:  shubhamkrm
linkedin_username:  shubham-kumaram

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
